version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "master"
    labels:
      - "dependencies"

  # NPM - Version 1
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "v1"
    labels:
      - "dependencies"

  # NPM - Version 2
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "v2"
    labels:
      - "dependencies"

  # NPM - Version 3
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "v3"
    labels:
      - "dependencies"
